// Generated by Wrangler on Sat Apr 13 2024 22:26:13 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AI: any;
}
